# Generated by Django 4.2.7 on 2026-08-13 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='App Name', max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android (.apk)'), ('ios', 'iOS (.ipa)'), ('windows', 'Windows (.exe)'), ('mac', 'macOS (.dmg)'), ('linux', 'Linux (.deb/.rpm)'), ('web', 'Web App'), ('other', 'Other')], max_length=20)),
                ('version', models.CharField(help_text='e.g., 2.1.0', max_length=20)),
                ('short_description', models.CharField(help_text='Brief description shown in listing', max_length=300)),
                ('description', models.TextField(help_text='Full description of the app')),
                ('features', models.TextField(blank=True, help_text='Key features (comma-separated)')),
                ('download_file', models.FileField(help_text='Upload your app file (.apk, .exe, .zip, etc.)', upload_to='apps/')),
                ('file_size', models.CharField(blank=True, help_text='e.g., 25 MB', max_length=50)),
                ('download_count', models.IntegerField(default=0)),
                ('latest_release_notes', models.TextField(blank=True, help_text="What's new in this version")),
                ('app_icon', models.ImageField(help_text='App icon (recommended: 512x512)', upload_to='apps/icons/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='apps/banners/')),
                ('screenshots', models.JSONField(default=list, help_text='List of screenshot URLs')),
                ('is_free', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('requirements', models.TextField(blank=True, help_text='System requirements')),
                ('supported_languages', models.CharField(blank=True, help_text='e.g., English, French, Spanish', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('beta', 'Beta Testing'), ('deprecated', 'Deprecated')], default='active', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('website_url', models.URLField(blank=True, help_text='App website or landing page')),
                ('documentation_url', models.URLField(blank=True, help_text='User guide or documentation')),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository')),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('release_date', models.DateField()),
                ('last_updated', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', '-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Dell XPS 15 2024', max_length=200)),
                ('brand', models.CharField(choices=[('dell', 'Dell'), ('hp', 'HP'), ('lenovo', 'Lenovo'), ('apple', 'Apple'), ('acer', 'Acer'), ('asus', 'ASUS'), ('msi', 'MSI'), ('other', 'Other')], max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('new', 'Brand New'), ('like-new', 'Like New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('processor', models.CharField(help_text='e.g., Intel Core i7-13700H', max_length=200)),
                ('ram', models.CharField(help_text='e.g., 16GB DDR5', max_length=50)),
                ('storage', models.CharField(help_text='e.g., 512GB SSD', max_length=100)),
                ('screen_size', models.CharField(help_text='e.g., 15.6 inch', max_length=20)),
                ('screen_resolution', models.CharField(blank=True, max_length=50)),
                ('graphics', models.CharField(blank=True, max_length=200)),
                ('battery_life', models.CharField(blank=True, max_length=50)),
                ('operating_system', models.CharField(choices=[('windows', 'Windows 11 Pro'), ('windows-home', 'Windows 11 Home'), ('macos', 'macOS'), ('linux', 'Linux'), ('chrome', 'Chrome OS'), ('none', 'No OS')], max_length=20)),
                ('year', models.IntegerField(help_text='Manufacturing year')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the computer')),
                ('condition_description', models.TextField(blank=True, help_text='Describe any wear, scratches, etc.')),
                ('main_image', models.ImageField(upload_to='computers/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='computers/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='computers/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='computers/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('quantity_available', models.IntegerField(default=1)),
                ('warranty', models.CharField(blank=True, help_text='e.g., 6 months', max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('sold_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-is_featured', 'order', '-added_date'],
            },
        ),
        migrations.CreateModel(
            name='Graphics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the design', max_length=200)),
                ('category', models.CharField(choices=[('logo', 'Logo Design'), ('flyer', 'Flyer Design'), ('banner', 'Banner Design'), ('poster', 'Poster Design'), ('business_card', 'Business Card'), ('social_media', 'Social Media Post'), ('branding', 'Branding'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of the design')),
                ('image', models.ImageField(help_text='Upload your design image', upload_to='graphics/')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComputerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_contact', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('any', 'Any')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New Inquiry'), ('read', 'Read'), ('replied', 'Replied'), ('interested', 'Interested'), ('not-interested', 'Not Interested')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='core.computer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
